### ISSUE TITLE
[Schema Inaccuracy] incorrect enum value for `filter` query parameter (`GET /issues`, `GET /orgs/{org}/issues`, `GET /user/issues`)

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#244]
# Schema Inaccuracy

The `repos` enum value was added recently. It is not described in the description. What is it doing?

```yml
      - name: filter
        description: "Indicates which sorts of issues to return. Can be one of:  \n\\*
          `assigned`: Issues assigned to you  \n\\* `created`: Issues created by you
          \ \n\\* `mentioned`: Issues mentioning you  \n\\* `subscribed`: Issues you're
          subscribed to updates for  \n\\* `all`: All issues the authenticated user
          can see, regardless of participation or creation"
        in: query
        required: false
        schema:
          type: string
          enum:
          - assigned
          - created
          - mentioned
          - subscribed
          - repos
          - all
          default: assigned
```

## Expected

Either amend the description or remove the enum value if it was added in error

**Comment by mattpage** [comment]
This is fixed

**Comment by gr2m** [comment]
@mattpage I still see the `repos` enum value in all three schemas at https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml

**Comment by gr2m** [comment]
ah I see the description is amended in https://github.com/github/rest-api-description/pull/475
