### ISSUE TITLE
[Schema Inaccuracy] GPL-3.0-or-later license spec for version 3 of SPDX

### ISSUE THREAD

**Issue by japhir** [github/rest-api-description#2460]
# Schema Inaccuracy

The API example on https://docs.github.com/en/rest/licenses?apiVersion=2022-11-28#get-all-commonly-used-licenses shows that it would return 

```
{
    "key": "gpl-3.0",
    "name": "GNU General Public License v3.0",
    "spdx_id": "GPL-3.0",
    "url": "https://api.github.com/licenses/gpl-3.0",
    "node_id": "MDc6TGljZW5zZW1pdA=="
  }
```

## Expected

The spdx website https://spdx.org/licenses/ says at the bottom that this notation for the GPL-3 license has been deprecated on their end starting with spdx Release 3.0.

They now expect:

Full name | Identifier 
-- | -- 
[GNU General Public License v1.0 only](https://spdx.org/licenses/GPL-1.0-only.html) 	| GPL-1.0-only 	
[GNU General Public License v1.0 or later](https://spdx.org/licenses/GPL-1.0-or-later.html) 	| GPL-1.0-or-later 	
[GNU General Public License v2.0 only](https://spdx.org/licenses/GPL-2.0-only.html) 	| GPL-2.0-only 	
[GNU General Public License v2.0 or later](https://spdx.org/licenses/GPL-2.0-or-later.html) 	| GPL-2.0-or-later 	
[GNU General Public License v3.0 only](https://spdx.org/licenses/GPL-3.0-only.html) 	| GPL-3.0-only 	
[GNU General Public License v3.0 or later](https://spdx.org/licenses/GPL-3.0-or-later.html) 	| GPL-3.0-or-later 	

so the API should update the spdx_id field.

This is specifically an issue if you want to have Zenodo github integration as recommended in https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content 

See this issue for the specifics of my use-case: https://github.com/zenodo/zenodo/issues/2451

**Comment by japhir** [comment]
I don't know what adding those labels means, but I think it's not just an issue with the documentation being different from what the API is doing (it's doing what it says it does) but an issue with the API not returning the latest SPDX database entry if I understand correctly.

**Comment by japhir** [comment]
This issue was resolved by updating my CITATION.cff file with GPL-3.0-or-later as a license field.

**Comment by ozak** [comment]
@ahoglund it seems the issue raised by @japhir is still not resolved. And at least in my case, his proposed solution did not work because the `CITATION.cff` file is not being passed to the release. I tried adding it to the release, but it still failed and generated the "Invalid value gpl-3.0.".

It is as if the citation file is not taken into account. Here's what it shows:
<img width="1233" alt="image" src="https://github.com/user-attachments/assets/361f659e-5cee-4362-b0cb-c9d240187689">

and here is my [`CITATION.cff`](https://github.com/human-mobility-index/hmi/blob/main/CITATION.cff).

In my main branch, I see the `CITATION.cff` file, but not in the tagged release as shown below.

<img width="941" alt="image" src="https://github.com/user-attachments/assets/a4dc4f66-bc7f-42d7-b2ba-fc18a6809ad1">
<img width="943" alt="image" src="https://github.com/user-attachments/assets/9b41f945-b26e-437a-9085-81d8ee13b99c">

Are other people not encountering this license issue? I did not find any other open/resolved issues.
